"""
models/ticket.py — Pydantic schemas for ticket request and response.

These are the data shapes used at the API boundary:
- TicketRequest: what the client sends
- ProcessedTicket: what the API returns after AI processing + workflow routing
- TicketListItem: lightweight version used in list responses
"""

from pydantic import BaseModel, EmailStr, Field
from datetime import datetime
from enum import Enum


# ---------------------------------------------------------------------------
# Enums — constrain AI output values for type safety
# ---------------------------------------------------------------------------

class TicketClassification(str, Enum):
    """Categories a support ticket can be assigned to."""
    BILLING = "billing"
    TECHNICAL = "technical"
    ACCOUNT = "account"
    SHIPPING = "shipping"
    GENERAL = "general"
    # Extended categories for workflow routing
    OUTAGE = "outage"
    ENTERPRISE_SALES = "enterprise_sales"
    CANCELLATION = "cancellation"
    REFUND = "refund"
    FEATURE_REQUEST = "feature_request"
    BUG_REPORT = "bug_report"
    INTEGRATION_PROBLEM = "integration_problem"


class TicketPriority(str, Enum):
    """Urgency levels for a support ticket."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"
    URGENT = "urgent"


class TicketSentiment(str, Enum):
    """Customer emotional tone detected in the message."""
    POSITIVE = "positive"
    NEUTRAL = "neutral"
    NEGATIVE = "negative"
    ANGRY = "angry"


# ---------------------------------------------------------------------------
# Request schema — incoming POST /tickets body
# ---------------------------------------------------------------------------

class TicketRequest(BaseModel):
    """
    Data the client submits when creating a new support ticket.
    All fields are required to ensure meaningful AI processing.
    """
    customer_name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Full name of the customer submitting the ticket.",
        examples=["Jan Kowalski"],
    )
    email: EmailStr = Field(
        ...,
        description="Customer email address.",
        examples=["jan@example.com"],
    )
    message: str = Field(
        ...,
        min_length=10,
        max_length=5000,
        description="The support message or issue description.",
        examples=["My invoice is wrong, I was charged twice this month."],
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "customer_name": "Jan Kowalski",
                "email": "jan@example.com",
                "message": "My invoice is wrong, I was charged twice this month. Please fix this urgently.",
            }
        }
    }


# ---------------------------------------------------------------------------
# Response schema — full processed ticket returned by POST /tickets
# ---------------------------------------------------------------------------

class ProcessedTicket(BaseModel):
    """
    Full ticket record after AI pipeline processing and workflow routing.
    Contains original request data, all AI-generated fields, and
    deterministic workflow orchestration fields.
    """
    ticket_id: str = Field(..., description="Unique ticket identifier (UUID).")
    customer_name: str
    email: str
    original_message: str = Field(..., description="The raw message submitted by the customer.")

    # AI-generated fields
    classification: TicketClassification = Field(..., description="Ticket category assigned by AI.")
    priority: TicketPriority = Field(..., description="Urgency level assigned by AI.")
    summary: str = Field(..., description="1-2 sentence summary of the issue.")
    sentiment: TicketSentiment = Field(..., description="Customer sentiment detected by AI.")
    suggested_response: str = Field(..., description="Draft reply for the customer support agent.")
    recommended_action: str = Field(..., description="Internal operational step recommended by AI.")

    # Workflow orchestration fields (deterministic, not AI-generated)
    assigned_team: str = Field(
        default="support_general",
        description="Team assigned to handle this ticket based on workflow rules.",
    )
    sla_hours: int = Field(
        default=24,
        description="SLA response window in hours based on classification and priority.",
    )
    requires_human_review: bool = Field(
        default=False,
        description="True if workflow rules determine human review is mandatory.",
    )
    escalation_level: int = Field(
        default=0,
        description="Escalation level: 0=normal, 1=elevated, 2=urgent escalation.",
    )
    internal_notes: str = Field(
        default="",
        description="Hardcoded routing notes generated by the workflow engine.",
    )

    # Metadata
    processed_at: datetime = Field(..., description="Server-side timestamp when processing completed.")
    ai_model_used: str = Field(..., description="The AI model identifier used for processing.")

    model_config = {
        "json_schema_extra": {
            "example": {
                "ticket_id": "550e8400-e29b-41d4-a716-446655440000",
                "customer_name": "Jan Kowalski",
                "email": "jan@example.com",
                "original_message": "My invoice is wrong, I was charged twice this month.",
                "classification": "billing",
                "priority": "high",
                "summary": "Customer reports a duplicate billing charge for the current month.",
                "sentiment": "negative",
                "suggested_response": "Dear Jan, we sincerely apologize for the inconvenience.",
                "recommended_action": "ESCALATE_TO_BILLING — Verify payment records.",
                "assigned_team": "finance_team",
                "sla_hours": 4,
                "requires_human_review": True,
                "escalation_level": 1,
                "internal_notes": "Billing/refund issue. Route to finance team.",
                "processed_at": "2024-01-15T10:30:00Z",
                "ai_model_used": "openai/gpt-4o-mini",
            }
        }
    }


# ---------------------------------------------------------------------------
# List item schema — lightweight version for GET /tickets list
# ---------------------------------------------------------------------------

class TicketListItem(BaseModel):
    """
    Condensed ticket representation for list views.
    Includes workflow routing fields for dashboard display.
    """
    ticket_id: str
    customer_name: str
    email: str
    classification: TicketClassification
    priority: TicketPriority
    sentiment: TicketSentiment
    processed_at: datetime
    # Workflow fields included for dashboard visibility
    assigned_team: str = Field(default="support_general")
    escalation_level: int = Field(default=0)
    requires_human_review: bool = Field(default=False)
